### Data Concatenation with Pandas

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    "id" : [1, 2, 3],
    "name" : ["Adam", "Bob", "Eve"],
})

df2 = pd.DataFrame({
    "id" : [4, 5, 6],
    "name" : ["Charlie", "Fester", "Gilian"],
})

In [6]:
pd.concat([df1, df2], axis = 0, ignore_index = True)

   id     name
0   1     Adam
1   2      Bob
2   3      Eve
3   4  Charlie
4   5   Fester
5   6   Gilian

In [7]:
pd.concat([df1, df2], axis = 1, ignore_index = True)

   0     1  2        3
0  1  Adam  4  Charlie
1  2   Bob  5   Fester
2  3   Eve  6   Gilian