### Melt and Pivot for Reshaping Data

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "country" : ["USA", "USA", "India", "India"],
    "year" : [2020, 2021, 2020, 2021],
    "sales" : [100, 120, 90, 110],
    "profit" : [20, 25, 18, 22],
})

In [7]:
melted_df = df.melt(id_vars = ["country", "year"], value_vars = ["sales", "profit"], var_name = "metrics", value_name = "value")
melted_df

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [9]:
original = melted_df.pivot_table(
    index = ["country", "year"],
    columns = "metrics",
    values = "value",
)
original

metrics       profit  sales
country year
India   2020    18.0   90.0
        2021    22.0  110.0
USA     2020    20.0  100.0
        2021    25.0  120.0